(() => {
    window.__CHATBOT_CONFIG__ = {
        // Backend API Endpoint
        // Using relative path for same-origin deployment on cloud server
        apiEndpoint: "/api/chat",
    };

    window.__CHATBOT_KB__ = {
        zh: {
            ui: {
                title: "简历助手",
                subtitlePro: "优先回答项目、技术栈与简历问题",
                subtitleFun: "兴趣交流模式（可选）",
                greetingPro: "你好！我是胡傲东的简历助手，可以回答项目、技术栈、随笔与联系信息。",
                greetingFun: "你好！这里是兴趣交流模式，可以聊传统文化、架空历史与星盘/塔罗（娱乐）。",
                inputPlaceholder: "输入问题，或点下面快捷入口",
                openLabel: "打开聊天",
                closeLabel: "关闭聊天",
                clearLabel: "清空",
                modePro: "专业",
                modeFun: "兴趣",
                switchToFun: "切到兴趣模式",
                switchToPro: "切到专业模式",
                funDisclaimer: "提示：星盘/塔罗仅供娱乐交流，不提供现实决策建议。",
                proGate: "我可以聊兴趣，但为了不影响应聘信息，建议切到“兴趣模式”。",
                unknown: "我更擅长项目与技术相关问题。你可以试试下面的快捷入口。",
                modeChangedPro: "已切换到专业模式。",
                modeChangedFun: "已切换到兴趣模式。",
                error: "抱歉，消息发送失败。可以稍后再试，或直接通过邮箱联系。",
            },
            labels: {
                projectsTitle: "项目概览",
                projectsIntro: "下面是我的三个主要项目：",
                projectDetail: "项目详情",
                stackTitle: "技术栈",
                resumeTitle: "简历要点",
                contactTitle: "联系信息",
                essaysTitle: "随笔与记录",
                hobbiesTitle: "兴趣方向",
                cultureTitle: "传统文化",
                historyTitle: "架空历史",
                tarotTitle: "星盘与塔罗",
                languages: "编程语言",
                systems: "系统与工具",
                ai: "AI / 多模态",
                env: "开发环境",
                email: "邮箱",
                phone: "电话",
                github: "GitHub",
                resumePage: "在线简历",
                resumePdf: "简历 PDF",
                essaysLink: "进入随笔列表",
            },
            actions: {
                projects: "问项目",
                stack: "聊技术栈",
                resume: "简历要点",
                essays: "看随笔",
                contact: "要联系方式",
                hobbies: "了解我(娱乐)",
                culture: "传统文化",
                history: "架空历史",
                tarot: "星盘&塔罗(娱乐)",
                modeFun: "切到兴趣",
                modePro: "切到专业",
            },
            profile: {
                summary: "跨平台客户端开发（Qt/QML、SwiftUI）、MVVM 架构与性能优化，具备从架构设计到产品交付的完整工程实践。",
                highlights: [
                    "跨平台客户端开发与系统架构设计",
                    "AI 多模态产品化（文本 → 视频等管线）",
                    "全栈交付与工程化落地",
                ],
            },
            projects: [
                {
                    id: "storytovideo",
                    name: "StoryToVideo",
                    summary: "跨平台 AI 视频生成系统（文本 → 分镜 → 图像/配音/视频）",
                    highlights: [
                        "任务网关 + 优先级队列，支持暂停/恢复/取消/重试",
                        "MVVM 分层设计（ViewModel/Network/Data 解耦）",
                        "8GB 显存下稳定生成 30s 720p，渲染帧率 60fps",
                    ],
                    stack: ["Qt/QML", "MVVM", "任务队列", "多模态渲染"],
                    link: "https://github.com/JadeSnow7/StoryToVideo",
                },
                {
                    id: "swiftsweep",
                    name: "SwiftSweep",
                    summary: "原生 macOS 系统优化工具（GUI + CLI）",
                    highlights: [
                        "统一清理链路：dry-run 预览、删除计划、审计日志",
                        "XPC Helper 权限隔离 + allowlist + symlink escape 防护",
                        "插件系统与相似媒体检测（pHash + LSH）",
                    ],
                    stack: ["SwiftUI", "SwiftPM", "XPC", "CLI/GUI"],
                    link: "https://github.com/JadeSnow7/SwiftSweep",
                },
                {
                    id: "graduation",
                    name: "AI 智能教学平台",
                    summary: "多端教学平台：桌面端 / H5 / iOS / Android",
                    highlights: [
                        "全栈交付：React 前端 + Go 后端 + Python AI 服务",
                        "Qwen3 + GraphRAG 构建知识图谱，答疑准确率 85%+",
                        "Docker Compose 一键部署，JWT + RBAC 权限体系",
                    ],
                    stack: ["React", "Go", "Python", "GraphRAG"],
                    link: "https://github.com/JadeSnow7/graduationDesign",
                },
            ],
            stack: {
                languages: ["C++", "Python", "Swift", "SystemVerilog"],
                systems: ["Docker", "Git", "LLVM（Familiar）", "GDB", "FPGA（Academic）", "Makefile"],
                ai: ["PyTorch", "OpenCV", "Ollama", "LLM", "TTS"],
                env: ["Windows", "macOS", "Linux"],
            },
            essays: {
                intro: "这里会记录学习、工程实践与思考过程。",
                link: "essays/index.html",
            },
            contact: {
                email: "1079249368@qq.com",
                phone: "18085741680",
                github: "https://github.com/JadeSnow7",
                resumePage: "resume.html",
                resumePdf: "assets/resume.pdf",
            },
            hobbies: {
                summary: "业余时间关注传统文化与架空历史创作，也会进行轻量的星盘/塔罗交流（娱乐向）。",
                culture: ["阅读经典与历史故事", "关注礼制/思想演进", "喜欢传统文化的当代解读"],
                history: ["世界观设定与社会制度推演", "技术与文明互动的假想历史", "偏重逻辑自洽与叙事节奏"],
                tarot: ["自我探索与娱乐交流", "不做现实决策建议"],
            },
        },
        en: {
            ui: {
                title: "Resume Assistant",
                subtitlePro: "Projects, stack, and resume Q&A",
                subtitleFun: "Interests mode (optional)",
                greetingPro: "Hi! I'm Hu Aodong's resume assistant. Ask about projects, tech stack, essays, or contacts.",
                greetingFun: "Hi! You're in interests mode—traditional culture, worldbuilding, and astrology/tarot (for fun).",
                inputPlaceholder: "Type a question or use quick actions",
                openLabel: "Open chat",
                closeLabel: "Close chat",
                clearLabel: "Clear",
                modePro: "Pro",
                modeFun: "Fun",
                switchToFun: "Switch to Fun",
                switchToPro: "Switch to Pro",
                funDisclaimer: "Note: astrology/tarot is for fun only, not real-life decisions.",
                proGate: "Happy to chat about hobbies, but I suggest switching to Fun mode.",
                unknown: "I’m best at projects and tech topics. Try a quick action below.",
                modeChangedPro: "Switched to Pro mode.",
                modeChangedFun: "Switched to Fun mode.",
                error: "Sorry, the message failed to send. Please try again later or contact me via email.",
            },
            labels: {
                projectsTitle: "Project Overview",
                projectsIntro: "Here are my three flagship projects:",
                projectDetail: "Project Detail",
                stackTitle: "Tech Stack",
                resumeTitle: "Resume Highlights",
                contactTitle: "Contact",
                essaysTitle: "Essays & Notes",
                hobbiesTitle: "Interests",
                cultureTitle: "Traditional Culture",
                historyTitle: "Worldbuilding",
                tarotTitle: "Astrology & Tarot",
                languages: "Languages",
                systems: "Systems & Tools",
                ai: "AI / Multimodal",
                env: "Dev Environment",
                email: "Email",
                phone: "Phone",
                github: "GitHub",
                resumePage: "Resume Page",
                resumePdf: "Resume PDF",
                essaysLink: "Go to Essays",
            },
            actions: {
                projects: "Projects",
                stack: "Tech Stack",
                resume: "Resume Highlights",
                essays: "Essays",
                contact: "Contact",
                hobbies: "Hobbies (Fun)",
                culture: "Traditional Culture",
                history: "Worldbuilding",
                tarot: "Astrology & Tarot (Fun)",
                modeFun: "Switch to Fun",
                modePro: "Switch to Pro",
            },
            profile: {
                summary: "Cross-platform client development (Qt/QML, SwiftUI), MVVM architecture, and performance optimization from system design to delivery.",
                highlights: [
                    "Cross-platform client development and system architecture",
                    "AI multimodal productization (text → video pipelines)",
                    "Full-stack delivery and engineering execution",
                ],
            },
            projects: [
                {
                    id: "storytovideo",
                    name: "StoryToVideo",
                    summary: "Cross-platform AI video generation pipeline (text → storyboard → image/voice/video)",
                    highlights: [
                        "Task gateway + priority queue with pause/resume/cancel/retry",
                        "MVVM layers (ViewModel/Network/Data) for testability",
                        "Stable 30s 720p on 8GB VRAM with 60fps rendering",
                    ],
                    stack: ["Qt/QML", "MVVM", "Task Queue", "Multimodal Rendering"],
                    link: "https://github.com/JadeSnow7/StoryToVideo",
                },
                {
                    id: "swiftsweep",
                    name: "SwiftSweep",
                    summary: "Native macOS optimization tool (GUI + CLI)",
                    highlights: [
                        "Unified cleanup pipeline: dry-run preview, deletion plan, audit logs",
                        "Privilege isolation via XPC helper + allowlist + symlink escape protection",
                        "Plugin system and similar-media detection (pHash + LSH)",
                    ],
                    stack: ["SwiftUI", "SwiftPM", "XPC", "CLI/GUI"],
                    link: "https://github.com/JadeSnow7/SwiftSweep",
                },
                {
                    id: "graduation",
                    name: "AI Teaching Platform",
                    summary: "Multi-client teaching platform: desktop / H5 / iOS / Android",
                    highlights: [
                        "Full-stack delivery: React FE + Go BE + Python AI services",
                        "Qwen3 + GraphRAG knowledge graph with 85%+ Q&A accuracy",
                        "Docker Compose deployment with JWT + RBAC",
                    ],
                    stack: ["React", "Go", "Python", "GraphRAG"],
                    link: "https://github.com/JadeSnow7/graduationDesign",
                },
            ],
            stack: {
                languages: ["C++", "Python", "Swift", "SystemVerilog"],
                systems: ["Docker", "Git", "LLVM (familiar)", "GDB", "FPGA (academic)", "Makefile"],
                ai: ["PyTorch", "OpenCV", "Ollama", "LLM", "TTS"],
                env: ["Windows", "macOS", "Linux"],
            },
            essays: {
                intro: "I share learning notes and engineering reflections here.",
                link: "essays/index.html",
            },
            contact: {
                email: "1079249368@qq.com",
                phone: "18085741680",
                github: "https://github.com/JadeSnow7",
                resumePage: "resume.html",
                resumePdf: "assets/resume.pdf",
            },
            hobbies: {
                summary: "I enjoy traditional culture and worldbuilding, plus light astrology/tarot chats (just for fun).",
                culture: ["Reading classics and historical stories", "Interest in rituals, institutions, and ideas", "Modern interpretations of tradition"],
                history: ["Worldbuilding and institutional design", "Speculative history of tech + civilization", "Logic-first storytelling"],
                tarot: ["Self-exploration and casual conversations", "No real-life decision advice"],
            },
        },
    };
})();
